accounts/urls.py
from django.conf.urls import patterns, url

from .views import _password_change, _login, logout_page, reset, reset_confirm, ProfileView, ProfileCreateView, ProfileUpdateView

urlpatterns = patterns(
    'project.accounts.views',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^profile/$', ProfileView.as_view(), name="detail"),
    url(r'^create/$', ProfileCreateView.as_view(), name="create"),
    url(r'^update/$', ProfileUpdateView.as_view(), name="update"),
    url(
        r'^login/?$',
        _login,
        {
            'template_name': 'registration/login.html'
        }, name="login"
    ),
    url(r'^logout/$', logout_page, name="logout"),
    url(r'^password/reset/$', reset, name="password_reset"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', reset_confirm, name="password_reset_confirm"),
    url(r'^password/change/$', _password_change, name="password_change"),
)

urlpatterns += patterns(
    '',

    # user forgot password
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name="password_reset_done"),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete'),

    # user password change
    url(r'^password/done/$', 'django.contrib.auth.views.password_change_done', name="password_change_done"),
)

final4010/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from core.views import HomepageView, QuizCreateView, QuizView

urlpatterns = [
    # Examples:
    # url(r'^$', 'final4010.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', HomepageView.as_view(), name="homepage"),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^quiz/(?P<pk>\d+)/$', QuizView.as_view(), name="quiz_detail"),
    url(r'^account/', include(admin.site.urls)),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.ForeignKey(User)
    address_1 = models.CharField(max_length=128)
    address_2 = models.CharField(max_length=128, null=True, blank=True)
    city = models.CharField(max_length=128)
    state = models.CharField(max_length=2)
    zip_code = models.CharField(max_length=32)
    phone = models.CharField(max_length=32)

    def __unicode__(self):
        return self.user.username

'''
passenger info:
    name
    address
    phone
    payment object
    account

Account:
    User FK (contrib.auth user)
    Address
    Phone
'''

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class ProfileForm(forms.Form):
    first_name = forms.fields.CharField(max_length=64, required=True)
    last_name = forms.fields.CharField(max_length=64, required=True)
    address_1 = forms.fields.CharField(max_length=128)
    address_2 = forms.fields.CharField(max_length=128, required=False)
    city = forms.fields.CharField(max_length=128)
    state = forms.fields.CharField(max_length=2)
    zip_code = forms.fields.CharField(max_length=32)
    phone = forms.fields.CharField(max_length=32)

    def clean(self):
        form_data = super(ProfileForm, self).clean()
        return form_data


class ProfileCreateForm(forms.Form):
    email = forms.fields.EmailField(max_length=128, required=True)
    password1 = forms.fields.CharField(label="Password", max_length=64, required=True, widget=forms.PasswordInput())
    password2 = forms.fields.CharField(label="Confirm Password", max_length=64, required=True, widget=forms.PasswordInput())

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email).count() > 0:
            raise forms.ValidationError(
                'That email address is already in use. Please enter a '
                'different email address.'
            )
        return email

accounts/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.views import login as auth_login
from django.contrib.auth.views import password_change, password_reset, password_reset_confirm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import DetailView
from django.views.generic.edit import FormView

from .forms import ProfileForm, ProfileCreateForm
from .mixins import LoginRequiredMixin
from .models import Profile


def logout_page(request):
    """
    Log users out and re-direct them to the main page.
    """
    logout(request)
    return HttpResponseRedirect('/')


def _password_change(request):
    return password_change(
        request,
        template_name='registration/password_change_form.html',
        post_change_redirect=reverse('accounts:detail'),
    )


def reset_confirm(request, uidb64=None, token=None):
    return password_reset_confirm(
        request,
        template_name='registration/password_reset_confirm.html',
        uidb64=uidb64,
        token=token,
        post_reset_redirect=reverse('accounts:login')
    )


def reset(request):
    return password_reset(
        request,
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
        post_reset_redirect=reverse('accounts:password_reset_done')
    )


def _login(request, *args, **kwargs):
    if request.method == 'POST':
        if not request.POST.get('remember_me', None):
            request.session.set_expiry(0)
    return auth_login(request, *args, **kwargs)


class ProfileView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "profile/detail.html"

    def get_object(self):
        if self.request.user.is_authenticated():
            return Profile.objects.get(user=self.request.user)
        else:
            return None

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileView, self).get_context_data(*args, **kwargs)
        return context


class ProfileCreateView(FormView):
    form_class = ProfileCreateForm
    template_name = "profile/create.html"
    success_url = '/'

    def get_success_url(self):
        return '/'

    def form_valid(self, form):
        form_data = form.cleaned_data
        email = form_data.pop('email')
        password = form_data.pop('password1')
        user_data = {
            'username': email,
            'email': email,
            'password': password,
        }
        user = User.objects.create_user(**user_data)
        user.save()
        authentication = authenticate(username=email, password=password)
        login(self.request, authentication)
        return HttpResponseRedirect(reverse('homepage'))


class ProfileUpdateView(LoginRequiredMixin, FormView):
    form_class = ProfileForm
    template_name = "profile/update.html"
    success_url = "/accounts/profile/"

    def get_form(self, form_class):
        user_data = Profile.objects.get(user=self.request.user).__dict__
        user_data.update({
            'first_name': (self.request.user.first_name or self.request.POST.get('first_name')),
            'last_name': (self.request.user.last_name or self.request.POST.get('last_name')),
            'email': (self.request.user.email or self.request.POST.get('email')),
        })
        return self.form_class(user_data)

    def form_valid(self, form):
        form_data = form.cleaned_data
        self.request.user.first_name = form_data.pop('first_name')
        self.request.user.last_name = form_data.pop('last_name')
        self.request.user.save()
        instance = Profile.objects.get(user=self.request.user)
        for attr, value in form_data.iteritems():
            setattr(instance, attr, value)
        instance.save()
        return HttpResponseRedirect(reverse('accounts:detail'))

accounts/templates/profile/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h1>Create an Account</h1>
        <form action="." method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary">Create Account</button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

accounts/templates/profile/detail.html
{% extends 'base.html' %}

{% block extra_styles %}
<style>
  .panel-body li {
    border: 1px solid #ddd;
    border-radius: 4px;
    margin-bottom: 5px;
    display: block;
  }
  ul {
    padding-left: 0;
  }
  .panel-body li a {
    display: inline-block;
    padding: 10px;
    width: 100%;
  }
  .panel-body a {
    color: #866115;
  }
  .panel-body p {
    color: #000;
  }
  .panel-body a:hover {
    color: rgba(167, 126, 37, 1);
  }
  .booking-link {
    font-size: 1.5em;
    font-weight: bold;
  }
  .card-done {
    color: green;
  }
  .panel-primary {
    border-top-color: rgb(232, 193, 112);
    border-left-color: rgb(232, 193, 112);
    border-right-color: rgb(232, 193, 112);
    border-bottom-color: rgb(232, 193, 112);
  }
  .panel-primary .panel-heading {
    color: black;
    border-top-color: rgb(232, 193, 112);
    border-bottom-color: rgb(232, 193, 112);
    border-left-color: rgb(232, 193, 112);
    border-right-color: rgb(232, 193, 112);
    background-color: rgb(232, 193, 112);
  }
  @media only screen and (max-width: 480px) {
    ul li span {
      display: block;
    }
  }
</style>
{% endblock extra_styles %}

{% block content %}
<div class="col-xs-12 col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><i class="fa fa-cog"></i> My Account</h3>
    </div>
    <div class="panel-body">
      <p>
        Logged in as {{ object.user.email }}. (<a href="{% url 'accounts:logout' %}">Not me?</a>)
      </p>
      <ul>
        <li><a href="{% url 'accounts:update' %}"><i class="fa fa-pencil"></i> Update My Profile</a></li>
        <li><a href="{% url 'accounts:password_change' %}"><i class="fa fa-lock"></i> Change Password</a></li>
      </ul>
    </div>
  </div>
  {% if passengers %}
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-car"></i> My Rides</h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for passenger in passengers %}
            <li>
              <a href="{% url 'rides:detail' passenger.ride.uuid passenger.uuid %}">
                <span>{{ passenger.ride.date }}:</span> {{ passenger.ride.schedule.starting_point }} - {{ passenger.ride.schedule.destination }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  {% endif %}
</div>
<div class="col-xs-12 col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">My Reward Points</h3>
    </div>
    <div class="panel-body">
      {% for card in cards %}
        <p>
        Free Ride #{{ forloop.counter }}:
        {% for point in card.point_list %}
          {% if point %}
            <span class="fa fa-stack card-done">
              <i class="fa fa-circle-o fa-stack-2x"></i>
              <i class="fa fa-check fa-stack-1x"></i>
            </span>
          {% else %}
            <span class="fa fa-stack">
              <i class="fa fa-circle-o fa-stack-2x"></i>
            </span>
          {% endif %}
        {% endfor %}
        </p>
      {% endfor %}
      {% if next_reward > 0 %}
        <p>You are {{ next_reward }} points away from your next free ride.</p>
        <p><a class="booking-link" href="{% url 'homepage' %}#form-container">Click here to start booking.</a></p>
      {% else %}
        <p>You've earned a free ride!
        <p><a class="booking-link" href="{% url 'homepage' %}#form-container">Click here to start booking.</a></p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/profile/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <ul class="breadcrumb">
    <li><a href="{% url 'accounts:detail' %}">My Account</a></li>
    <li class="active">Update My Profile</li>
  </ul>
  <h1>Updating My Profile</h1>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Changes</button>
  </form>
{% endblock content %}