accounts/urls.py
from django.conf.urls import patterns, url

from .views import _password_change, _login, logout_page, reset, reset_confirm, ProfileView, ProfileCreateView, ProfileUpdateView

urlpatterns = patterns(
    'project.accounts.views',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^profile/$', ProfileView.as_view(), name="detail"),
    url(r'^create/$', ProfileCreateView.as_view(), name="create"),
    url(r'^update/$', ProfileUpdateView.as_view(), name="update"),
    url(
        r'^login/?$',
        _login,
        {
            'template_name': 'registration/login.html'
        }, name="login"
    ),
    url(r'^logout/$', logout_page, name="logout"),
    url(r'^password/reset/$', reset, name="password_reset"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', reset_confirm, name="password_reset_confirm"),
    url(r'^password/change/$', _password_change, name="password_change"),
)

urlpatterns += patterns(
    '',

    # user forgot password
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name="password_reset_done"),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete'),

    # user password change
    url(r'^password/done/$', 'django.contrib.auth.views.password_change_done', name="password_change_done"),
)

final4010/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from core.views import HomepageView, QuizCreateView, QuizView

urlpatterns = [
    # Examples:
    # url(r'^$', 'final4010.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', HomepageView.as_view(), name="homepage"),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^quiz/(?P<pk>\d+)/$', QuizView.as_view(), name="quiz_detail"),
    url(r'^account/', include(admin.site.urls)),
]

core/models.py
import random
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.models import Group, User


def set_staff(sender, instance, **kwargs):
    instance.is_staff = True
pre_save.connect(set_staff, sender=User)

def set_group(sender, instance, **kwargs):
    if kwargs['created']:
        instance.groups.add(Group.objects.get(name="Site Users"))
        instance.save()
post_save.connect(set_group, sender=User)


class QuizAnswer(models.Model):
    question = models.ForeignKey('QuizQuestion')
    text = models.CharField(max_length=256)
    correct = models.BooleanField(default=False)

    def __unicode__(self):
        return self.text[:16]


class QuizQuestion(models.Model):
    quiz = models.ForeignKey('Quiz')
    question = models.CharField(max_length=128)

    @property
    def answers(self):
        return QuizAnswer.objects.filter(question__id=self.id)

    def __unicode__(self):
        return self.question[:16]


class Quiz(models.Model):
    author = models.ForeignKey(User, editable=False)
    title = models.CharField(max_length=32)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('quiz_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = "Quizzes"

    @property
    def questions(self):
        return QuizQuestion.objects.filter(quiz__id=self.id)

    def __unicode__(self):
        return self.title

core/views.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from django.views.generic import CreateView, DetailView, TemplateView
from django.http import HttpResponseRedirect

from .models import Quiz, QuizAnswer, QuizQuestion


class HomepageView(TemplateView):
    template_name = "base_home.html"

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data(**kwargs)
        context['quizzes'] = Quiz.objects.all()
        return context


class QuizView(DetailView):
    template_name = "quiz/take_quiz.html"
    model = Quiz


class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ('title', 'description')


QuestionFormSet = inlineformset_factory(Quiz, QuizQuestion, fields=('quiz', 'question'))
AnswerFormSet = inlineformset_factory(QuizQuestion, QuizAnswer, fields=('question', 'text', 'correct'))


class QuizCreateView(CreateView):
    template_name = "quiz/create.html"
    form_class = QuizForm

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        answer_form = AnswerFormSet()
        question_form = QuestionFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  answer_form=answer_form,
                                  question_form=question_form))

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        answer_form = AnswerFormSet(self.request.POST)
        question_form = QuestionFormSet(self.request.POST)
        if (
            form.is_valid() and
            answer_form.is_valid() and
            question_form.is_valid()
        ):
            return self.form_valid(form, answer_form, question_form)
        else:
            return self.form_invalid(form, answer_form, question_form)

    def form_valid(self, form, answer_form, question_form):
        """
        Called if all forms are valid. Creates a Recipe instance along with
        associated Ingredients and Instructions and then redirects to a
        success page.
        """
        self.object = form.save()
        answer_form.instance = self.object
        answer_form.save()
        question_form.instance = self.object
        question_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, answer_form, question_form):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form,
                                  answer_form=answer_form,
                                  question_form=question_form))

core/templates/base.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}{% endblock title %} | Study Crack</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <style>
            body {
                padding-top: 15px;
            }
        </style>
        {% block extra_styles %}{% endblock extra_styles %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        <div class="container">
            <nav class="navbar navbar-default navbar-inverse">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Study Crack</a>
                  </div>
                  <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                      <li class="{% block home-active %}active{% endblock home-active %}"><a href="/">Home</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                            <li><a href="/account/">Your Quizzes</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                            <li><a href="{% url 'accounts:create' %}">Register</a></li>
                        {% endif %}
                    </ul>
                  </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </nav>
        </div>
        {% block content %}{% endblock content %}


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.3.min.js"><\/script>')</script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        {% block extra_scripts %}{% endblock extra_scripts %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

core/templates/base_home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block extra_styles %}
  <style>
    .quiz-list {
      list-style: none;
      padding: 0;
    }
    .quiz-list li {
      border: 1px solid black;
      border-radius: 10px;
      margin-bottom: 10px;
    }
    .quiz-list li a {
      padding: 15px;
      display: block;
      color: black;
      transition: 200ms all;
      border-radius: 10px;
    }
    .quiz-list li a:hover {
      text-decoration: none;
      background: black;
      color: white;
    }
  </style>
{% endblock extra_styles %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <p>Welcome to Study Crack. A study guide with a minimalist UI.</p>
      </div>
      <div class="col-xs-12">
        <h2>Quizzes on Study Crack</h2>
        <ul class="quiz-list">
          {% for quiz in quizzes %}
            <li><a href="{% url 'quiz_detail' quiz.pk %}">{{ quiz.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}